default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: <%= ENV['THEMITCHELL_DATABASE_NAME'] %>

test:
  <<: *default
  database: <%= ENV['THEMITCHELL_DATABASE_NAME'] %>

production:
  <<: *default
  database: <%= ENV['THEMITCHELL_DATABASE_NAME'] %>
  username: <%= ENV['THEMITCHELL_DATABASE_USERNAME'] %>
  password: <%= ENV['THEMITCHELL_DATABASE_PASSWORD'] %>
